#!/usr/bin/env python3

import os
import sys

import helpers
from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile @username")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # import user's tweets and check
    username = sys.argv[1]
    tweets_list = helpers.get_user_timeline(username, 100)
    if tweets_list == None:
        sys.exit("Error, unable to access @usernames tweets")
        exit(1)
    
    # analyze each tweet and assign the respective color
    for tweet in tweets_list:
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print(colored(score, 'green'), colored(tweet, 'green'))
        
        elif score < 0.0:
            print(colored(score, 'red'), colored(tweet, 'red'))
        
        else:
            print(colored(score, 'yellow'), colored(tweet, 'yellow'))
            
if __name__ == "__main__":
    main()
